#!groovy
@Library('boot-service-ci-jenkins-shared-lib') _
def rootPom = 'pom.xml'
def goalsAndOptions = 'clean -U package'
def jarFilePath = 'test/target/proxy-test.jar'
def domeOSProjectName = 'mq-proxy'
def jvmArgs = ' -server -Xmx4g -Xms4g -Xss256k -DPROJECT_DIR=/data/\\${HOSTNAME} -XX:+UseG1GC -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -XX:MaxGCPauseMillis=100 -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -XX:+PrintCommandLineFlags -XX:-OmitStackTraceInFastThrow -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Djava.util.Arrays.useLegacyMergeSort=true -Dfile.encoding=UTF-8'
if (env.BRANCH_NAME == 'test') {
    buildBootServiceForDomeOS {
        delegate.rootPom = rootPom
        delegate.goalsAndOptions = goalsAndOptions
        delegate.jarFilePath = jarFilePath
        delegate.springProfile = 'test'
        delegate.jvmArgs = "-Dspring.profiles.active=test $jvmArgs"
        delegate.domeOSProjectName = domeOSProjectName
        delegate.pinpointArgs = '-Dpinpoint.applicationName=mq-proxy-tt -Dprofiler.sampling.rate=1'
    }
}
if (env.BRANCH_NAME == 'master') {
    buildBootServiceForDomeOS {
        delegate.rootPom = rootPom
        delegate.goalsAndOptions = goalsAndOptions
        delegate.jarFilePath = jarFilePath
        delegate.springProfile = 'online'
        delegate.jvmArgs = "-Dspring.profiles.active=online $jvmArgs"
        delegate.domeOSProjectName = domeOSProjectName
        delegate.pinpointArgs = '-Dpinpoint.applicationName=mq-proxy-test-online'
    }
}